version: '3'
services:
  api:
    build:
      context: .
      dockerfile: devenv/Dockerfile.api
    command: uwsgi uwsgi.ini --py-auto-reload 1 --worker-reload-mercy 5
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: temporary_password
      DB_NAME: postgres
    volumes:
      - ./uwsgi.ini:/opt/app-root/src/uwsgi.ini
      - ./api:/opt/app-root/src/api
  db:
    build:
      context: .
      dockerfile: devenv/Dockerfile.db
    restart: always
    environment:
      POSTGRES_PASSWORD: temporary_password
